public with sharing class AccountListControllerLwc {
    @AuraEnabled(cacheable=true)
    public static List<Account> queryAccountsByEmployeeNumber(Integer numberOfEmployees) {
        return [
            SELECT Name, NumberOfEmployees
            FROM Account
            WHERE NumberOfEmployees >= :numberOfEmployees
        ];
   }
   @AuraEnabled(cacheable=true)
   public static List<Account> queryAccountsByRevenue(Decimal annualRevenue){ 
        return [
            SELECT Name, AnnualRevenue
            FROM Account
            WHERE AnnualRevenue >= :annualRevenue
        ];
   }
}